homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.86.231:1883  # Rpi ip-adresse  
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_d00351860051e811a00701f8c2460985-if00-port0  # Smlight-SLZB-06 Device OR
    /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_422fb2a8588dec11b4576ce883c5466d-if00-port0   # Nabu Casa Zigbee Device OR
  port: tcp://192.168.86.20:6638  # zigbee dongle ip-adresse. If you use Smlight-SLZB-06 via Ethernet. 
  adapter: zstack   # For Smlight-SLZB-06 use zstack and for SkyConnect use ezsp. 
  baudrate: 115200
  disable_led: false
# transmit_power: 20
frontend: true
# port: 8081
# host: 192.168.86.231
advanced:
  network_key: GENERATE
  pan_id: GENERATE

